---
title: Turning a kymograph into tidy data using the tidyverse in R
thumbnailImagePosition: left
thumbnailImage: /post/2018-02-27-Import-tidy-plot_files/figure-html/ridge-plot-1.png
author: Ali Twelvetrees
date: '2018-02-27'
categories:
  - R
tags:
  - kymographs
  - ggplot2
  - image analysis
  - R
---



<p>I have a bit of a love hate relationship with kymographs. In the way that they compress data there’s no doubt that you loose information, but in the world of axonal transport and low signal:noise they have clear advantages in enabling quantification.</p>
<p>I covered before a couple of strategies you can use to <a href="http://dozenoaks.ghost.io/importing-images-into-r/">import image data into R</a>. The next step in my workflow is usually to turn that image into a data table for further analysis. A data table can take many forms, but I think the easiest and most powerful way to get the most out of R these days is to use the tidyverse collection of packages.</p>
<p>I picked up R a few years ago now and since then I’ve happily watched the tidyverse grow and develop. It is a fantastic set of tools accessible to anyone, and it’s easy to see the parallels between ImageJ/FIJI development and the R/tidyverse. To work happily within the tidyverse your data does have to be tidy. Tidy data is a standardized way of mapping the meaning of data to it’s structure (across lots of different types of data). A simple concept in essence, I remember it taking me a while to fully transition from spreadsheets until the penny really dropped. Tidy data is data that conforms to the following rules:</p>
<ol style="list-style-type: decimal">
<li>Each variable describing the data forms a separate column.</li>
<li>Each observation forms a row and all the parameters you need to describe that observation should be on that row.</li>
<li>Each type of observational unit forms a table.</li>
</ol>
<p>If your a beginner to R it’s worth reading Hadley Whickham’s paper on <a href="https://www.jstatsoft.org/article/view/v059i10">Tidy Data</a>, a very straight forward and useful read.</p>
<p>This is my strategy to turn an image into tidy data for downstream analysis. First up, load the packages we need. The <code>tidyverse</code> package loads a suite of (currently) 26 packages, but in this example I’m only actually using functions from <code>tibble</code>, <code>tidyr</code>, <code>forcats</code> and <code>ggplot2</code>. I’m also loading <code>EBImage</code> to <a href="http://dozenoaks.ghost.io/importing-images-into-r/">import my data</a>:</p>
<pre class="r"><code>library(tidyverse)
library(EBImage)

kymograph &lt;- readImage(&quot;MAX_Reslice_of_low_pass_axon_16bit.tif&quot;, type = &quot;tiff&quot;)
display(kymograph, method = &quot;raster&quot;)</code></pre>
<p><img src="/post/2018-02-27-Import-tidy-plot_files/figure-html/load-packages-and-import-1.png" width="672" /></p>
<p>This image is 950 pixels wide and 181 pixels high.</p>
<p>Turning the image into a data table is easy enough, in this case I will turn it into a tibble - the tidyverse class for storing a data frame - which is faster than <code>as.data.frame()</code> used in base R.</p>
<pre class="r"><code>#&#39; Turn the kymograph tif into a tibble
kymo_data &lt;- as_tibble(kymograph)
#&#39; Take a quick peek
kymo_data</code></pre>
<pre><code>## # A tibble: 950 x 181
##       V1    V2    V3    V4    V5    V6    V7    V8    V9   V10   V11   V12
##    &lt;dbl&gt; &lt;dbl&gt; &lt;dbl&gt; &lt;dbl&gt; &lt;dbl&gt; &lt;dbl&gt; &lt;dbl&gt; &lt;dbl&gt; &lt;dbl&gt; &lt;dbl&gt; &lt;dbl&gt; &lt;dbl&gt;
##  1 0.228 0.153 0.253 0.195 0.215 0.308 0.251 0.322 0.277 0.258 0.185 0.278
##  2 0.195 0.165 0.238 0.190 0.230 0.284 0.234 0.273 0.232 0.252 0.189 0.257
##  3 0.178 0.195 0.201 0.178 0.205 0.277 0.213 0.241 0.230 0.251 0.178 0.242
##  4 0.165 0.192 0.157 0.212 0.173 0.292 0.199 0.228 0.195 0.253 0.232 0.273
##  5 0.160 0.205 0.153 0.182 0.130 0.282 0.190 0.231 0.166 0.232 0.256 0.315
##  6 0.161 0.246 0.188 0.181 0.137 0.244 0.196 0.228 0.153 0.235 0.275 0.312
##  7 0.166 0.247 0.199 0.170 0.152 0.187 0.216 0.250 0.161 0.259 0.221 0.295
##  8 0.187 0.201 0.174 0.182 0.164 0.179 0.237 0.263 0.190 0.301 0.229 0.272
##  9 0.195 0.160 0.156 0.185 0.180 0.200 0.253 0.244 0.193 0.301 0.208 0.237
## 10 0.175 0.139 0.148 0.192 0.191 0.193 0.258 0.237 0.186 0.251 0.171 0.263
## # ... with 940 more rows, and 169 more variables: V13 &lt;dbl&gt;, V14 &lt;dbl&gt;,
## #   V15 &lt;dbl&gt;, V16 &lt;dbl&gt;, V17 &lt;dbl&gt;, V18 &lt;dbl&gt;, V19 &lt;dbl&gt;, V20 &lt;dbl&gt;,
## #   V21 &lt;dbl&gt;, V22 &lt;dbl&gt;, V23 &lt;dbl&gt;, V24 &lt;dbl&gt;, V25 &lt;dbl&gt;, V26 &lt;dbl&gt;,
## #   V27 &lt;dbl&gt;, V28 &lt;dbl&gt;, V29 &lt;dbl&gt;, V30 &lt;dbl&gt;, V31 &lt;dbl&gt;, V32 &lt;dbl&gt;,
## #   V33 &lt;dbl&gt;, V34 &lt;dbl&gt;, V35 &lt;dbl&gt;, V36 &lt;dbl&gt;, V37 &lt;dbl&gt;, V38 &lt;dbl&gt;,
## #   V39 &lt;dbl&gt;, V40 &lt;dbl&gt;, V41 &lt;dbl&gt;, V42 &lt;dbl&gt;, V43 &lt;dbl&gt;, V44 &lt;dbl&gt;,
## #   V45 &lt;dbl&gt;, V46 &lt;dbl&gt;, V47 &lt;dbl&gt;, V48 &lt;dbl&gt;, V49 &lt;dbl&gt;, V50 &lt;dbl&gt;,
## #   V51 &lt;dbl&gt;, V52 &lt;dbl&gt;, V53 &lt;dbl&gt;, V54 &lt;dbl&gt;, V55 &lt;dbl&gt;, V56 &lt;dbl&gt;,
## #   V57 &lt;dbl&gt;, V58 &lt;dbl&gt;, V59 &lt;dbl&gt;, V60 &lt;dbl&gt;, V61 &lt;dbl&gt;, V62 &lt;dbl&gt;,
## #   V63 &lt;dbl&gt;, V64 &lt;dbl&gt;, V65 &lt;dbl&gt;, V66 &lt;dbl&gt;, V67 &lt;dbl&gt;, V68 &lt;dbl&gt;,
## #   V69 &lt;dbl&gt;, V70 &lt;dbl&gt;, V71 &lt;dbl&gt;, V72 &lt;dbl&gt;, V73 &lt;dbl&gt;, V74 &lt;dbl&gt;,
## #   V75 &lt;dbl&gt;, V76 &lt;dbl&gt;, V77 &lt;dbl&gt;, V78 &lt;dbl&gt;, V79 &lt;dbl&gt;, V80 &lt;dbl&gt;,
## #   V81 &lt;dbl&gt;, V82 &lt;dbl&gt;, V83 &lt;dbl&gt;, V84 &lt;dbl&gt;, V85 &lt;dbl&gt;, V86 &lt;dbl&gt;,
## #   V87 &lt;dbl&gt;, V88 &lt;dbl&gt;, V89 &lt;dbl&gt;, V90 &lt;dbl&gt;, V91 &lt;dbl&gt;, V92 &lt;dbl&gt;,
## #   V93 &lt;dbl&gt;, V94 &lt;dbl&gt;, V95 &lt;dbl&gt;, V96 &lt;dbl&gt;, V97 &lt;dbl&gt;, V98 &lt;dbl&gt;,
## #   V99 &lt;dbl&gt;, V100 &lt;dbl&gt;, V101 &lt;dbl&gt;, V102 &lt;dbl&gt;, V103 &lt;dbl&gt;, V104 &lt;dbl&gt;,
## #   V105 &lt;dbl&gt;, V106 &lt;dbl&gt;, V107 &lt;dbl&gt;, V108 &lt;dbl&gt;, V109 &lt;dbl&gt;,
## #   V110 &lt;dbl&gt;, V111 &lt;dbl&gt;, V112 &lt;dbl&gt;, …</code></pre>
<p>My data table has 950 rows and 181 columns. I admit I have never been entirely clear on why the width of your image ends up as rows in this operation (and have not been sufficiently motivated to find out), but it doesn’t really matter as long as you know the orientation of the data.</p>
<p>The one thing this tibble isn’t at present is tidy. Each pixel in the original image has it’s grey value represented in the table, but if you mixed up the rows and the columns you would have no way of knowing what the position of any one pixel had been in x and y. Tidy data demands that not only does the row contain your grey value, it also contains the position in x and y. How do we do that?</p>
<p>First things first, I need to add a column that describes explicitly what the row number currently means - the position along the x axis in the image. There are many ways to add a column. You can use the <code>$</code> in base R or the <code>mutate()</code> function from <code>dplyr</code>: <code>kymo_data$Pixel_position &lt;- 1:nrow(kymo_data)</code> or <code>kymo_data &lt;- mutate(kymo_data, Pixel_position = 1:nrow(kymo_data))</code></p>
<p>These are both fine, except that they both append a column to the end of the table. In order to be able to fully automate the process of import and conversion, I want to specify the position of the column in the table and have it be the first column. This is because the next operation is to reshape the data so that the column names become a new column describing the position on the y axis, and this is much easier if I can tell the reshaping function to act on every column after the first with the description <code>2:last column</code>, where the last column is the same as the number of columns in the table using <code>ncol</code>. The <code>add_column</code> function from the tibble package lets me do this with the <code>.before</code> command. The <code>gather</code> command from the <code>tidyr</code> package then reshapes the data. If we take a peek at the table after this it looks totally different.</p>
<pre class="r"><code>#&#39; Add a column describing the pixel number as the first colum in the table
kymo_data &lt;- add_column(kymo_data, Pixel_position = 1:nrow(kymo_data), .before = 1)

#&#39; Reshape the table so intensity values are in one column (this is why I put the `Pixel` column first)
kymo_data &lt;- gather(kymo_data, 2:ncol(kymo_data), key = &quot;Time_point&quot;, value = &quot;Intensity&quot;)
kymo_data</code></pre>
<pre><code>## # A tibble: 171,950 x 3
##    Pixel_position Time_point Intensity
##             &lt;int&gt; &lt;chr&gt;          &lt;dbl&gt;
##  1              1 V1             0.228
##  2              2 V1             0.195
##  3              3 V1             0.178
##  4              4 V1             0.165
##  5              5 V1             0.160
##  6              6 V1             0.161
##  7              7 V1             0.166
##  8              8 V1             0.187
##  9              9 V1             0.195
## 10             10 V1             0.175
## # ... with 171,940 more rows</code></pre>
<p>This is very very close to the finished tidy data. There is one last step. The column names are currently character strings in the <code>Time_point</code> column rather than numerical time points. The column names when I converted the image to a tibble were listed as <code>V1</code>, <code>V2</code>, <code>V3</code> etc because column names aren’t allowed to be numbers in R. So basically I want to get rid of the V and turn the character into a number. I could do this by using string functions to get rid of the <code>V</code>, but as the list here is ordered what I’m going to do instead is turn the <code>Time_points</code> into ordered factors and then turn the factor levels into their numeric equivalent.</p>
<pre class="r"><code>#&#39; We can check the nature of the values the column with the is.character function
is.character(kymo_data$Time_point)</code></pre>
<pre><code>## [1] TRUE</code></pre>
<pre class="r"><code>#&#39; Now we tell the characters to become factors with the as_factor function
kymo_data$Time_point &lt;- as_factor(kymo_data$Time_point)
#&#39; Just check they are factors
is.factor(kymo_data$Time_point)</code></pre>
<pre><code>## [1] TRUE</code></pre>
<pre class="r"><code>#&#39; Now turn the factors into numbers
kymo_data$Time_point &lt;- as.numeric(kymo_data$Time_point)
is.numeric(kymo_data$Time_point)</code></pre>
<pre><code>## [1] TRUE</code></pre>
<pre class="r"><code>kymo_data</code></pre>
<pre><code>## # A tibble: 171,950 x 3
##    Pixel_position Time_point Intensity
##             &lt;int&gt;      &lt;dbl&gt;     &lt;dbl&gt;
##  1              1         1.     0.228
##  2              2         1.     0.195
##  3              3         1.     0.178
##  4              4         1.     0.165
##  5              5         1.     0.160
##  6              6         1.     0.161
##  7              7         1.     0.166
##  8              8         1.     0.187
##  9              9         1.     0.195
## 10             10         1.     0.175
## # ... with 171,940 more rows</code></pre>
<p>And it’s done - The kymograph is now tidy data. But why on earth would you want to do such a thing?!? Well, all the steps I’ve just walked through can be automated into one wrapper function. You don’t need to think this hard every time. And once your data is in the table you can start the real work of analysis. You also get to do cool things like this:</p>
<pre class="r"><code>library(ggridges)

plot &lt;- kymo_data %&gt;% ggplot(., aes(x = Pixel_position, y = max(Time_point)-Time_point, group = Time_point, height = Intensity))
plot + 
  geom_ridgeline(scale = 5, fill = &quot;#33CCCC&quot;, colour = &quot;white&quot;, size = 0.25) + 
  coord_cartesian(xlim = c(300, 800)) +
  theme_classic() +
  theme(axis.title = element_blank(),
        axis.text = element_blank(),
        axis.ticks = element_blank(),
        axis.line = element_blank(),
        panel.background = element_rect(fill = &quot;#33CCCC&quot;),
        panel.border = element_blank(),
        panel.spacing = unit(c(0,0,0,0),&quot;cm&quot;)
  )</code></pre>
<p><img src="/post/2018-02-27-Import-tidy-plot_files/figure-html/ridge-plot-1.png" width="672" /></p>
<p>The <code>ggridges</code> package was created as a <code>ggplot2</code> extension to allow ridge line plots, specifically plots inspired by the Joy Division <em>Unknown Pleasures</em> album cover (the resulting plots were originally called joy plots). I had been messing around with trying to create a version of this plot for some of my kymograph data, just because I thought it would look cool. <code>ggridges</code> is far more elegant than my solution, although the jury is out on whether this is anything other than an aesthetic plot at this point, I do like it.</p>
<p>In the process of my research though I did discover that the history of that original plot is quite interesting. I had at some point thought that the <em>Unknown Pleasures</em> stacked plot was actually Dame Jocelyn Bell Burnell’s representation of a pulsar - turns out I was wrong. It was created by Harold Craft, a radio astronomer at the Arecibo Radio Observatory. For fellow data presentation nerds I thoroughly recommend the following two articles; <a href="https://adamcap.com/2011/05/19/history-of-joy-division-unknown-pleasures-album-art/">Adam Cap’s own account</a> of his hunt for the origin of the image and the <a href="https://blogs.scientificamerican.com/sa-visual/pop-culture-pulsar-origin-story-of-joy-division-s-unknown-pleasures-album-cover-video/">Origin story by Jen Christiansen</a> over at Scientific American. Finally, here is an extract from Craft on the stacked plots:</p>
<blockquote>
<p>So, the thought was, well, is there something like this peak here, which on the next pulse moves over here, and then moves over here, and over there … So, then the thought was, well let’s plot out a whole array of pulses, and see if we can see particular patterns in there. So that’s why, this one was the first I did – CP1919 – and you can pick out patterns in there if you really work at it. But I think the answer is, there weren’t any that were real obvious anyway.</p>
</blockquote>
<p>I think what’s interesting is that they were looking for things moving with these plots, and that is absolutely what a kymograph is for. What’s good enough for pulsars is good enough for axonal transport :) And if anyone wants to gift me a neon kymograph for the office wall, that would be awesome…</p>
<div align="center">
<p><img src="/img/2018-02-27/neon.jpg" alt="Neon light at Burger and Lobster in Manchester (Image: Gary Louth, Manchester Evening News)" /> <a href="https://www.manchestereveningnews.co.uk/whats-on/joy-division-artwork-hacienda-sign-14344682">“Burger and Lobster” in Manchester (Image: Gary Louth, Manchester Evening News)</a></p>
</div>
